---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/9 14:02
---

local debug = {}

debug.handles = {}
debug.gchashes = {}

function debug.handle_ref(handle)
    debug.handles[handle.handle_id] = handle
end

function debug.gchash(class, handle)
    debug.gchashes[class] = handle
end

function debug.handle_unref(handle)
    debug.handles[handle.handle_id] = nil
end

function debug.handlemax()
    local max = 0
    for k, _ in pairs(debug.handles) do
        if k > max then
            max = k
        end
    end
    return max
end

function debug.handlecount()
    local count = 0
    for _, _ in pairs(debug.handles) do
        count = count + 1
    end
    return count
end

return debug