---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lianghao.
--- DateTime: 2022/6/8 23:41
---

package.path = package.path .. ';test_frame/?.lua;'

print(package.path)

require 'jass.log'

require('main')

local trigger_util = require 'jass.util.trigger_util'
local player = require 'jass.type.player'
local item = require 'jass.type.item'
local unit = require 'jass.type.unit'
local player_unit_event = require 'jass.type.playerunitevent'
local player_event = require 'jass.type.playerevent'
local unit_event = require 'jass.type.unitevent'
local timer = require 'jass.type.timer'
local common = require 'jass.common'

function before_test()
    timer.update(1)
end

function test_select_hero()
    trigger_util.trig_player_unit_event(player[1], player_unit_event[24], K4[1])
    trigger_util.trig_player_unit_event(player[1], player_unit_event[24], K4[1])
    print(udg_hero[1].id)
end

function test_join_denom()
    log.debug('选择门派')
    trigger_util.trig_player_unit_event(player[1], player_unit_event[49], udg_hero[1], { manipulated_item = item.create(1227894834, 0, 0) })
end

function test_change_camera()
    trigger_util.trig_player_chat_event(player[1], '+')
    trigger_util.trig_player_chat_event(player[1], '-')
    trigger_util.trig_player_chat_event(player[1], '+ys')
    trigger_util.trig_player_chat_event(player[1], '+js')
    trigger_util.trig_player_chat_event(player[1], 'sj')
end

function test_town_portal()
    trigger_util.trig_player_chat_event(player[1], 'hg')
    trigger_util.trig_player_chat_event(player[1], 'q')
    trigger_util.trig_player_chat_event(player[1], '3')
    trigger_util.trig_player_chat_event(player[1], '4')
end

function test_self_make_weapon()
    log.debug('按键输入')
    trigger_util.trig_player_chat_event(player[1], 'wq')
    common.UnitAddItemById(udg_hero[1], 1227899464)
    trigger_util.trig_player_chat_event(player[1], 'wq')
end

function test_check_exclusive()
    trigger_util.trig_player_chat_event(player[1], 'ckzs')
end

function test_check_damage()
    trigger_util.trig_player_chat_event(player[1], 'ck')
end

function test_qian_kun()
    common.UnitAddAbility(udg_hero[1], 1093678935)
    trigger_util.trig_player_chat_event(player[1], '1')
    trigger_util.trig_player_chat_event(player[1], '2')
end

function test_key_input()

    --trigger_util.trig_player_chat_event(player[1], 'tx1' )
    --trigger_util.trig_player_chat_event(player[1], 'wg' )
    --trigger_util.trig_player_chat_event(player[1], 'ckch' )
    --trigger_util.trig_player_chat_event(player[1], 'ckwg' )
    --trigger_util.trig_player_chat_event(player[1], 'ckwq' )
    --trigger_util.trig_player_chat_event(player[1], 'ckjn' )

    --trigger_util.trig_player_chat_event(player[1], 'sort' )
    --trigger_util.trig_player_chat_event(player[1], 'ver' )
    --trigger_util.trig_player_chat_event(player[1], 'cx' )
    --trigger_util.trig_player_chat_event(player[1], 'cxs' )

    --trigger_util.trig_player_chat_event(player[1], '-ms' )
    --trigger_util.trig_player_chat_event(player[1], 'www.juezhanjianghu.com' )
    trigger_util.trig_player_chat_event(player[1], 'ckjf')
    trigger_util.trig_player_chat_event(player[1], '累积积分')
    trigger_util.trig_player_chat_event(player[1], 'baolv')
    trigger_util.trig_player_chat_event(player[1], 'fb')
    trigger_util.trig_player_chat_event(player[1], 'bl')
    trigger_util.trig_player_chat_event(player[1], 'yx')
    trigger_util.trig_player_chat_event(player[1], 'jy')

end

function test_random_denom()
    trigger_util.trig_player_chat_event(player[1], '-random')
end

function test_choose_murong()
    trigger_util.trig_player_chat_event(player[1], 'jzjh.uuu9.com')
end

function test_check_prop()
    trigger_util.trig_player_chat_event(player[1], 'fy9')
    trigger_util.trig_player_chat_event(player[1], 'wx2')
    trigger_util.trig_player_chat_event(player[1], 'gg2')
    trigger_util.trig_player_chat_event(player[1], 'jm2')
    trigger_util.trig_player_chat_event(player[1], 'dp2')
    trigger_util.trig_player_chat_event(player[1], 'ys2')
    trigger_util.trig_player_chat_event(player[1], 'cksx')
end

function test_mall()
    trigger_util.trig_player_chat_event(player[1], 'testMall')
end

function test_test_code()
    udg_isTest[0] = true
    trigger_util.trig_player_chat_event(player[1], '贼哥牛逼')
    trigger_util.trig_player_chat_event(player[1], '撸Boss8')
    trigger_util.trig_player_chat_event(player[1], 'n7')
    print(udg_nandu)
    print(shengwang[1])
end

function test_clean()
    trigger_util.trig_player_chat_event(player[1], '-clean')
    trigger_util.trig_player_chat_event(player[1], '-clean')
    trigger_util.trig_player_chat_event(player[1], '-clean')
end

function test_show_hp()
    trigger_util.trig_player_chat_event(player[1], 'qxts')
    print(showHint[1])
    trigger_util.trig_player_chat_event(player[1], 'kqts')
    print(showHint[1])
    SaveReal(YDHT, GetHandleId(gg_unit_N007_0055), 4077, 90)
    trigger_util.trig_player_unit_event(player[1], player_unit_event[24], gg_unit_N007_0055)

end

function test_use_dan()
    --for i = 1, 11 do
    --    trigger_util.trig_player_unit_event(player[1], player_unit_event[50], udg_hero[1],  {manipulated_item = item.create(1227895375, 0, 0)})
    --end
    --print(yishu[1])
    --trigger_util.trig_player_unit_event(player[1], player_unit_event[50], udg_hero[1],  {manipulated_item = item.create(1227896410, 0, 0)})

    -- 黑玉断续膏
    print(common.GetHeroInt(udg_hero[1], true))
    trigger_util.trig_player_unit_event(player[1], player_unit_event[50], udg_hero[1], { manipulated_item = item.create(1227895888, 0, 0) })
    print(common.GetHeroInt(udg_hero[1], true))
    trigger_util.trig_player_unit_event(player[1], player_unit_event[50], udg_hero[1], { manipulated_item = item.create(1227895888, 0, 0) })

    -- 生生造化丹
    print(common.GetHeroAgi(udg_hero[1], true))
    trigger_util.trig_player_unit_event(player[1], player_unit_event[50], udg_hero[1], { manipulated_item = item.create(1227895886, 0, 0) })
    print(common.GetHeroAgi(udg_hero[1], true))
    trigger_util.trig_player_unit_event(player[1], player_unit_event[50], udg_hero[1], { manipulated_item = item.create(1227895886, 0, 0) })

    -- 绝元丹
    print(juexuelingwu[1])
    trigger_util.trig_player_unit_event(player[1], player_unit_event[50], udg_hero[1], { manipulated_item = item.create(1227896406, 0, 0) })
    print(juexuelingwu[1])
    trigger_util.trig_player_unit_event(player[1], player_unit_event[50], udg_hero[1], { manipulated_item = item.create(1227896406, 0, 0) })


end

function test_equipment()
    local it = item.create(1227897145, 0, 0)
    common.SetItemUserData(it, 111111111)
    trigger_util.trig_player_unit_event(player[1], player_unit_event[49], udg_hero[1], { manipulated_item = it })

    it = item.create(1227897153, 0, 0)
    trigger_util.trig_player_unit_event(player[1], player_unit_event[49], udg_hero[1], { manipulated_item = it })
end

function test_suits()
    common.UnitAddItemById(udg_hero[1], 1227895116)

    print(UnitHaveItem(udg_hero[1], 1227895116))
    --common.UnitAddItemById(udg_hero[1],1227897153)
    --trigger_util.trig_player_unit_event(player[1], player_unit_event[49], udg_hero[1], { manipulated_item = item.create(1227895116, 0, 0) })
    common.UnitAddItemById(udg_hero[1], 1227895117)

    local it = item.create(1227895117, 0, 0)
    it.level = 1
    trigger_util.trig_player_unit_event(player[1], player_unit_event[49], udg_hero[1], { manipulated_item = it })
    print(UnitHaveItem(udg_hero[1], 1227895117))

end

function test_switch_item()
    print(P4[1])
    trigger_util.trig_player_unit_event(player[1], player_unit_event[273], P4[1], { spell_ability_id = base.string2id('A00M') })
end

function test_levelup()
    common.UnitAddAbility(udg_hero[1], 1093678407)
    for i = 1, 500 do
        --common_ability.kungfu_levelup(et.unit(udg_hero[1]), 1093678407, 1200)
        WuGongShengChong(udg_hero[1], 1093678407, 1200)
        print("升重进度：", i, et.unit(udg_hero[1]).skill_str[base.id2string(1093678407)])
    end
    trigger_util.trig_player_chat_event(player[1], 'ckjn')
end

function test_damage()
    common.UnitAddAbility(udg_hero[1], 1093678407)
    print('三围：', common.GetHeroStr(udg_hero[1], true), common.GetHeroAgi(udg_hero[1], true), common.GetHeroInt(udg_hero[1], true))
    local damage = ShangHaiGongShi(udg_hero[1], udg_hero[1], 10, 12, 1, 1093678407)
    print('造成伤害：', damage)

    common.SetHeroStr(udg_hero[1], 100, true)
    common.SetHeroAgi(udg_hero[1], 100, true)
    common.SetHeroInt(udg_hero[1], 100, true)
    print('三围：', common.GetHeroStr(udg_hero[1], true), common.GetHeroAgi(udg_hero[1], true), common.GetHeroInt(udg_hero[1], true))
    damage = ShangHaiGongShi(udg_hero[1], udg_hero[1], 10, 12, 1, 1093678407)
    print('造成伤害：', damage)

    common.SetHeroStr(udg_hero[1], 1000, true)
    common.SetHeroAgi(udg_hero[1], 1000, true)
    common.SetHeroInt(udg_hero[1], 1000, true)
    print('三围：', common.GetHeroStr(udg_hero[1], true), common.GetHeroAgi(udg_hero[1], true), common.GetHeroInt(udg_hero[1], true))
    damage = ShangHaiGongShi(udg_hero[1], udg_hero[1], 10, 12, 1, 1093678407)
    print('造成伤害：', damage)

    common.SetHeroStr(udg_hero[1], 10000, true)
    common.SetHeroAgi(udg_hero[1], 10000, true)
    common.SetHeroInt(udg_hero[1], 10000, true)
    print('三围：', common.GetHeroStr(udg_hero[1], true), common.GetHeroAgi(udg_hero[1], true), common.GetHeroInt(udg_hero[1], true))
    damage = ShangHaiGongShi(udg_hero[1], udg_hero[1], 10, 12, 1, 1093678407)
    print('造成伤害：', damage)

    -- 测试极限伤害
    common.UnitAddAbility(udg_hero[1], 1093678390)
    common.UnitAddAbility(udg_hero[1], 1093678393)
    common.SetUnitAbilityLevel(udg_hero[1], 1093678390, 9)
    common.SetUnitAbilityLevel(udg_hero[1], 1093678393, 9) -- 神龙心法
    common.UnitAddItemById(udg_hero[1], 1227900229) -- 十四天书
    udg_lilianxishu[1] = 20
    special_attack[1] = 42
    udg_shanghaijiacheng[1] = 2

    common.SetHeroStr(udg_hero[1], 10000, true)
    common.SetHeroAgi(udg_hero[1], 10000, true)
    common.SetHeroInt(udg_hero[1], 10000, true)
    print('三围：', common.GetHeroStr(udg_hero[1], true), common.GetHeroAgi(udg_hero[1], true), common.GetHeroInt(udg_hero[1], true))
    damage = ShangHaiGongShi(udg_hero[1], udg_hero[1], 8, 11, 1, 1093678390)
    print('造成伤害：', damage)
end

function test_kill_dahan()
    trigger_util.trig_player_unit_event(player[1], player_unit_event[20], unit.create(player[7], base.string2id('n016'), 0, 0, 270), { killer = udg_hero[1] })
end

before_test()

test_select_hero()
test_join_denom()

--test_key_input()
--test_change_camera()
--test_use_dan()
--test_check_prop()
--test_suits()
--test_switch_item()
test_town_portal()

local u = udg_hero[1]
local p = common.GetOwningPlayer(u)
UnitAddAbility(u, 1093679441)
DisplayTextToPlayer(p, 0, 0, "|cFFFFCC00使用新手大礼包获得神行状态")
et.wait(10 * 1000, function()
    UnitRemoveAbility(u, 1093679441)
    DisplayTextToPlayer(p, 0, 0, "|cFFFF0000失去神行效果")
end)

timer.update(10)

local hero = et.unit.j_unit(udg_hero[1])
hero:add_status('无妄')

print(hero:has_status('无妄'))

hero:add_ability('A083')
hero:add_ability('A09D')
hero:add_ability('A0D8')

print('暴伤：', udg_baojishanghai[1])
print('金钱', hero:get_owner():get_gold())
print('木材', hero:get_owner():get_lumber())
print('内力', hero:get_agi())
print(wuxing[1])
print(gengu[1])
print(fuyuan[1])
print(danpo[1])
print(jingmai[1])
print(yishu[1])
trigger_util.trig_player_unit_event(player[7], player_unit_event[18], unit.create(player[7], base.string2id('n016'), 0, 0, 270), { attacker = udg_hero[1] })

print('暴伤：', udg_baojishanghai[1])
print('金钱', hero:get_owner():get_gold())
print('木材', hero:get_owner():get_lumber())
print('内力', hero:get_agi())
print(wuxing[1])
print(gengu[1])
print(fuyuan[1])
print(danpo[1])
print(jingmai[1])
print(yishu[1])
--test_kill_dahan()
--test_mall()
--test_random_denom()

-- 1000秒 触发魔教救人
--timer.update(1000)
--generate_map()







