---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lianghao.
--- DateTime: 2022/6/8 23:41
---

package.path = package.path .. ';test_frame/?.lua;'

print(package.path)

require 'jass.log'

